name: Daily Tech News Digest

on:
  schedule:
    - cron: '0 2 * * 1-5'  # 2 AM UTC daily (9 AM UTC+7)
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tech News Digest Bot
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TOGETHER_API_KEY_summarizer: ${{ secrets.TOGETHER_API_KEY_summarizer }}
          TOGETHER_API_KEY_chunker: ${{ secrets.TOGETHER_API_KEY_chunker }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

        run: |
          python main.py --generate

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
